import { eq } from 'drizzle-orm'
import { Podcast } from "podcast"
import { queryUserListenLaterList } from "./listen_later"
import { queryPlaylistByPlaylistId, queryPlaylistItemsByPlaylistId } from "./playlist"
import { UserPlaylistItemDto } from "../models/playlist"
import { FeedItem } from "../models/feeds"
import { UserInfo } from "../api/user/types"
import { UserListenLaterDto } from "../models/listen_later"
import { queryKeywordSubscriptionFeedItemList, queryUserKeywordSubscriptionDetail } from "./subscription"
import * as schema from './schema'

type DbClient = ReturnType<typeof import('./client').createDb>

export const generateListenLaterRSSXml = async (db: DbClient, userId: string): Promise<string> => {
  const userInfo = await db
    .select()
    .from(schema.userInfo)
    .where(eq(schema.userInfo.id, userId))
    .limit(1)

  if (userInfo.length === 0) {
    throw new Error('User not found')
  }

  const user = userInfo[0]
  const queryListData = await queryUserListenLaterList(db, userId, 200, 0)
  const serverUserInfo: UserInfo = {
    userId: user.id,
    nickname: user.nickname || '',
    email: user.email || '',
    phone: user.phone || '',
    avatar: user.avatar || '',
    telegramId: user.telegramId || '',
    password: "",
    regDate: user.regDate ? new Date(user.regDate) : new Date(),
    updateDate: user.updateDate ? new Date(user.updateDate) : new Date(),
  }

  const nickname = serverUserInfo.nickname
  const feed = new Podcast({
    title: `${nickname}\`s Porkast Listen Later`,
    language: queryListData[0]?.country || 'en',
    description: `${nickname}\`s Porkast Listen Later, generated by Porkast`,
    feedUrl: `https://porkast.com/api/rss/listenlater/${userInfo[0].id}`,
    siteUrl: 'https://porkast.com',
    imageUrl: 'https://porkast.com/porkast-text-logo.png',
    author: nickname,
    managingEditor: nickname,
    webMaster: 'Porkast',
    copyright: `${nickname}@Porkast`,
    itunesAuthor: nickname,
    itunesOwner: { email: user.email || '', name: nickname },
    itunesSubtitle: `${nickname}\`s Porkast Listen Later`,
    itunesImage: 'https://porkast.com/porkast-text-logo.png',
  })

  queryListData.forEach((item: UserListenLaterDto) => {
    feed.addItem({
      title: item.title,
      description: item.description,
      url: item.link,
      guid: item.guid,
      author: item.author,
      date: item.pub_date,
      enclosure: {
        url: item.enclosure_url,
        size: parseInt(item.enclosure_length || '0'),
        type: item.enclosure_type
      },
      itunesAuthor: item.author,
      itunesExplicit: false,
      itunesSummary: item.description,
      itunesImage: item.image_url,
      itunesSeason: parseInt(item.season || '0'),
      itunesDuration: item.duration,
      itunesNewFeedUrl: item.feed_link
    })
  })

  return feed.buildXml()
}

export const generatePlaylistRSSXml = async (db: DbClient, userId: string, playlistId: string): Promise<string> => {
  const userInfo = await db
    .select()
    .from(schema.userInfo)
    .where(eq(schema.userInfo.id, userId))
    .limit(1)

  if (userInfo.length === 0) {
    throw new Error('User not found')
  }

  const user = userInfo[0]
  const serverUserInfo: UserInfo = {
    userId: user.id,
    nickname: user.nickname || '',
    email: user.email || '',
    phone: user.phone || '',
    avatar: user.avatar || '',
    telegramId: user.telegramId || '',
    password: "",
    regDate: user.regDate ? new Date(user.regDate) : new Date(),
    updateDate: user.updateDate ? new Date(user.updateDate) : new Date(),
  }
  const nickname = serverUserInfo.nickname

  const playlistInfoQuery = await queryPlaylistByPlaylistId(db, playlistId)
  if (!playlistInfoQuery) {
    throw new Error('Playlist not found')
  }

  const playlistItemList = await queryPlaylistItemsByPlaylistId(db, playlistId)

  const feed = new Podcast({
    title: `${playlistInfoQuery.PlaylistName}`,
    language: 'en',
    description: `${playlistInfoQuery.Description}\n\n${nickname}\`s Porkast Playlist , generated by Porkast`,
    feedUrl: `https://porkast.com/api/rss/playlist/${playlistId}/${userInfo[0].id}`,
    siteUrl: 'https://porkast.com',
    imageUrl: 'https://porkast.com/porkast-text-logo.png',
    author: nickname,
    managingEditor: nickname,
    webMaster: 'Porkast',
    copyright: `${nickname}@Porkast`,
    itunesAuthor: nickname,
    itunesOwner: { email: user.email || '', name: nickname },
    itunesSubtitle: `${nickname}\`s Porkast Playlist, ${playlistInfoQuery.PlaylistName}`,
    itunesImage: 'https://porkast.com/porkast-text-logo.png',
  })

  playlistItemList.forEach((item: UserPlaylistItemDto) => {
    feed.addItem({
      title: item.Title,
      description: item.Description,
      url: item.Link,
      guid: item.GUID,
      author: item.Author,
      date: item.PubDate,
      enclosure: {
        url: item.EnclosureUrl,
        size: parseInt(item.EnclosureLength || '0'),
        type: item.EnclosureType
      },
      itunesAuthor: item.Author,
      itunesExplicit: false,
      itunesSummary: item.Description,
      itunesImage: item.ImageUrl,
      itunesSeason: parseInt(item.Season || '0'),
      itunesDuration: item.Duration,
      itunesNewFeedUrl: item.FeedLink
    })
  })

  return feed.buildXml()
}

export const generateSubscriptionRSS = async (db: DbClient, userId: string, keyword: string): Promise<string> => {
  const userInfo = await db
    .select()
    .from(schema.userInfo)
    .where(eq(schema.userInfo.id, userId))
    .limit(1)

  if (userInfo.length === 0) {
    throw new Error('User not found')
  }

  const user = userInfo[0]
  const serverUserInfo: UserInfo = {
    userId: user.id,
    nickname: user.nickname || '',
    email: user.email || '',
    phone: user.phone || '',
    avatar: user.avatar || '',
    telegramId: user.telegramId || '',
    password: "",
    regDate: user.regDate ? new Date(user.regDate) : new Date(),
    updateDate: user.updateDate ? new Date(user.updateDate) : new Date(),
  }
  const nickname = serverUserInfo.nickname

  const subsciptionInfo = await queryUserKeywordSubscriptionDetail(db, userId, keyword)
  if (!subsciptionInfo) {
    throw new Error('Subscription not found')
  }

  const decodeKeyword = decodeURIComponent(keyword)
  const [subsciptionItemList, totalCount] = await queryKeywordSubscriptionFeedItemList(db, userId, keyword, subsciptionInfo.Source, subsciptionInfo.Country, subsciptionInfo.ExcludeFeedId, 0, 200)

  const feed = new Podcast({
    title: `${subsciptionInfo.Keyword}`,
    language: 'en',
    description: `${nickname}\`s Porkast Search Subscription with ${subsciptionInfo.Keyword}, generated by Porkast`,
    feedUrl: `https://porkast.com/api/rss/subscription/${decodeKeyword}/${userInfo[0].id}`,
    siteUrl: 'https://porkast.com',
    imageUrl: 'https://porkast.com/porkast-text-logo.png',
    author: nickname,
    managingEditor: nickname,
    webMaster: 'Porkast',
    copyright: `${nickname}@Porkast`,
    itunesAuthor: nickname,
    itunesOwner: { email: user.email || '', name: nickname },
    itunesSubtitle: `${nickname}\`s Porkast Search Subscription with ${subsciptionInfo.Keyword}, generated by Porkast`,
    itunesImage: 'https://porkast.com/porkast-text-logo.png',
  })

  subsciptionItemList.forEach((item: FeedItem) => {
    feed.addItem({
      title: item.Title,
      description: item.Description,
      url: item.Link,
      guid: item.GUID,
      author: item.Author,
      date: item.PubDate,
      enclosure: {
        url: item.EnclosureUrl,
        size: parseInt(item.EnclosureLength || '0'),
        type: item.EnclosureType
      },
      itunesAuthor: item.Author,
      itunesExplicit: false,
      itunesSummary: item.Description,
      itunesImage: item.ImageUrl,
      itunesSeason: parseInt(item.Season || '0'),
      itunesDuration: item.Duration,
      itunesNewFeedUrl: item.FeedLink
    })
  })

  return feed.buildXml()
}
